### PR TITLE
Somehow the ping command was bugged... fixed it

### PR DESCRIPTION
**Pull request by GianniKoch**
As the title said, ping command was bugged, but I fixed it :D

### CODE REVIEW

**Comment by ErisApps** [comment]
Yeah... no.

**Comment by GianniKoch** [comment]
You cannot keep avoiding it @ErisApps CUTE!

**Comment by GianniKoch** [comment]
I still think this is a bug...

**Comment by grYs51** [comment]
@ErisApps cute

**Comment by GianniKoch** [comment]
@grYs51 not so cute :(

**Pull request closed without merging**
